remote_theme: pages-themes/primer
title: Flag Predictor
description: A website that runs an AI model to predict the differential and OURCs Flags for rowing in Oxford
url: "https://flagpredictor.com"
baseurl: ""
